name: matrix_dart_chatgpt
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/krille-chan/matrix-dart-chatgpt

environment:
  sdk: ^3.1.0

dependencies:
  chat_gpt_sdk: ^3.1.5
  matrix: ^2.0.1
  sqflite_common_ffi: ^2.3.6
  vodozemac: ^0.2.0

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.21.0
